### ISSUE TITLE
Question: Any other way to get the diagram

### ISSUE THREAD

**Issue by xasz** [cscaminaci/HaloPSASQLSchema#1]
Hello,

thanks for your work - this looks promissing.
Is ther any other way to get this instead of having a png ?
Some json or any kind of searchable content ?

**Comment by cscaminaci** [comment]
Hi Michael,

This was made with dbForge Studio and unfortunately they do not have a way to export in any other format. You can hook dbForge up to your HaloPSA read only database account and use that as a searchable interactive diagram.
________________________________
From: Michael Schneider ***@***.***>
Sent: Thursday, December 7, 2023 6:07:25 AM
To: cscaminaci/HaloPSASQLSchema ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cscaminaci/HaloPSASQLSchema] Question: Any other way to get the diagram (Issue #1)


Hello,

thanks for your work - this looks promissing.
Is ther any other way to get this instead of having a png ?
Some json or any kind of searchable content ?

**Comment by xasz** [comment]
well i will do that :) thank you for the info
